name: CI-docker-only

on:
  push:
    branches: [ "main" ]
  pull_request: {}

jobs:
  test-docker:
    runs-on: macos-latest
    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.5.0
